"""Edge-case test: calls every tool with bad or odd input and fails if any reply is a raw Python error
(IndexError, KeyError, TypeError ...) instead of a clear message. Run it before a release:

    POSELAB_BLENDER=/path/to/blender python examples/edge_cases.py
"""
import os
import re
import sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "benchmarks"))
from mcp_stdio import PoseLab
RAW = re.compile(r"KeyError|TypeError|AttributeError|IndexError|ZeroDivision|UnboundLocal|NoneType|bpy_prop|RecursionError|ValueError: math domain|not subscriptable|object is not|unexpected keyword|Traceback")
lab = PoseLab()
bad = []
def t(_label, _tool, **a):
    r = lab.call(_tool, **a)
    txt = " ".join(c.get("text", "") for c in r["content"] if c["type"] == "text")
    flag = r.get("isError") and (RAW.search(txt) or "Error executing tool %s" % _tool == txt.strip())
    if flag: bad.append((_label, txt[:300]))
    print("%-4s %-40s %s" % ("BUG" if flag else ("err" if r.get("isError") else "ok"), _label, txt[:150].replace("\n", " ")))
# before any rig
t("describe before load", "describe")
t("pose_idle before load", "pose_idle")
t("render before load", "render")
t("anatomy before load", "anatomy")
t("arm_ranges before load", "arm_ranges")
t("load unknown rig", "load_rig", rig="nope")
t("load sample", "load_rig", rig="sample")
t("list_rigs", "list_rigs")
t("pose_clip unknown", "pose_clip", clip="nope", seconds=0)
t("move_part unknown", "move_part", part="nope", cm=1)
t("move_part huge", "move_part", part="carrier", cm=1e6)
t("move_gun unknown pivot", "move_gun", roll=10, pivot="nope")
t("move_gun pivot list short", "move_gun", roll=10, pivot=[1, 2])
t("move_gun keep_hands bad", "move_gun", roll=10, keep_hands=["x"])
t("move_gun nan-ish huge", "move_gun", roll=1e9)
t("pose_idle", "pose_idle")
t("reach bad side", "reach", side="x", target=[0, 30, 0])
t("reach unknown point", "reach", side="l", target="nope")
t("reach target short list", "reach", side="l", target=[1, 2])
t("reach pole short", "reach", side="l", target=[10, 30, 0], pole=[1])
t("reach far", "reach", side="l", target=[1e6, 0, 0])
t("reach at shoulder (zero length)", "reach", side="l", target=[23, -28, -1])
t("pose_idle", "pose_idle")
t("snapshot load missing", "snapshot", action="load", name="nope")
t("snapshot bad action", "snapshot", action="x", name="a")
t("where empty", "where", names=[])
t("where bad frame", "where", names=["port"], frame="x")
t("where list point", "where", names=[[1, 2, 3]])
t("distance same", "distance", a="port", b="port")
t("distance unknown", "distance", a="nope", b="port")
t("clearance bad parts", "clearance", parts="x")
t("clearance top 0", "clearance", top=0)
t("clearance ignore all", "clearance", ignore=["*"])
t("anatomy", "anatomy")
t("anatomy one side", "anatomy", side="l")
t("anatomy bad side", "anatomy", side="x")
t("anatomy no fingers", "anatomy", fingers=False)
t("faces_eye unknown", "faces_eye", point="nope")
t("faces_eye zero normal", "faces_eye", point="port", normal=[0, 0, 0])
t("faces_eye point without normal", "faces_eye", point="muzzle")
t("faces_eye list point no normal", "faces_eye", point=[0, 30, 0])
t("visible radius 0", "visible", point="port", radius_cm=0)
t("visible radius neg", "visible", point="port", radius_cm=-1)
t("screen behind eye", "screen", point=[0, -200, 0])
t("screen unknown", "screen", point="nope")
t("solve empty dofs", "solve", dofs={}, goals=[{"type": "on_screen", "point": "port"}], samples=5)
t("solve unknown dof", "solve", dofs={"x": [0, 1]}, goals=[{"type": "on_screen", "point": "port"}], samples=5)
t("solve bad range", "solve", dofs={"roll": [10]}, goals=[{"type": "on_screen", "point": "port"}], samples=5)
t("solve empty goals", "solve", dofs={"roll": [0, 10]}, goals=[], samples=5)
t("solve unknown goal", "solve", dofs={"roll": [0, 10]}, goals=[{"type": "x"}], samples=5)
t("solve goal no point", "solve", dofs={"roll": [0, 10]}, goals=[{"type": "faces_eye"}], samples=5)
t("solve maximize out of range", "solve", dofs={"roll": [0, 10]}, goals=[{"type": "on_screen", "point": "port"}], samples=5, maximize=5)
t("solve samples 0", "solve", dofs={"roll": [0, 10]}, goals=[{"type": "on_screen", "point": "port"}], samples=0)
t("solve samples 1", "solve", dofs={"roll": [0, 10]}, goals=[{"type": "faces_eye", "point": "port", "min": 0.5}], samples=1)
t("solve anatomy goal", "solve", dofs={"roll": [0, 10]}, goals=[{"type": "anatomy"}], samples=3)
t("solve anatomy bad side", "solve", dofs={"roll": [0, 10]}, goals=[{"type": "anatomy", "side": "x"}], samples=3)
t("pose_idle", "pose_idle")
t("record key before start", "record_clip", action="key", seconds=0)
t("record stop before start", "record_clip", action="stop")
t("record start no name", "record_clip", action="start")
t("record start", "record_clip", action="start", clip="c1")
t("record stop no keys", "record_clip", action="stop")
t("record start2", "record_clip", action="start", clip="c2")
t("record key", "record_clip", action="key", seconds=0)
t("record stop one key", "record_clip", action="stop")
t("record start3", "record_clip", action="start", clip="c3")
t("record key 0", "record_clip", action="key", seconds=0)
t("record key same time", "record_clip", action="key", seconds=0)
t("record key negative", "record_clip", action="key", seconds=-1)
t("record key 1", "record_clip", action="key", seconds=1)
t("record fps 0", "record_clip", action="stop", fps=0)
t("record stop c3", "record_clip", action="stop")
t("pose_clip c3 beyond", "pose_clip", clip="c3", seconds=99)
t("pose_clip c3 negative", "pose_clip", clip="c3", seconds=-5)
t("load_clip missing file", "load_clip", clip="x", path="C:/nope/nope.pose.json")
t("load_clip bad ext", "load_clip", clip="x", path="C:/Windows/win.ini")
t("scan missing clip", "scan_clip", clip="nope", checks=[{"type": "pop"}])
t("scan empty checks", "scan_clip", clip="c3", checks=[])
t("scan unknown check", "scan_clip", clip="c3", checks=[{"type": "x"}])
t("scan hold no side", "scan_clip", clip="c3", checks=[{"type": "hold"}])
t("scan hold bad side", "scan_clip", clip="c3", checks=[{"type": "hold", "side": "x"}])
t("scan contact missing a", "scan_clip", clip="c3", checks=[{"type": "contact"}])
t("scan during bad", "scan_clip", clip="c3", checks=[{"type": "pop", "during": [5]}])
t("scan pop empty bones", "scan_clip", clip="c3", checks=[{"type": "pop", "bones": []}])
t("scan hold ref beyond", "scan_clip", clip="c3", checks=[{"type": "hold", "side": "l", "ref_s": 99}])
t("grip", "grip")
t("grip one side", "grip", side="l")
t("grip strict", "grip", back_max_cm=0, palm_max_cm=0, hold_within_cm=0)
t("grip bad side", "grip", side="x")
t("solve grip goal", "solve", dofs={"roll": [0, 10]}, goals=[{"type": "grip"}], samples=3)
t("scan grip", "scan_clip", clip="c3", checks=[{"type": "grip"}])
t("fix grip (scan only)", "fix_clip", clip="c3", checks=[{"type": "grip"}])
t("scan anatomy", "scan_clip", clip="c3", checks=[{"type": "anatomy"}])
t("scan anatomy bad side", "scan_clip", clip="c3", checks=[{"type": "anatomy", "side": "x"}])
t("fix missing", "fix_clip", clip="nope", checks=[{"type": "pop"}])
t("fix empty checks", "fix_clip", clip="c3", checks=[])
t("fix one-frame clip", "fix_clip", clip="c2", checks=[{"type": "pop"}, {"type": "hold", "side": "l"}])
t("fix spread 0", "fix_clip", clip="c3", checks=[{"type": "hold", "side": "l"}], spread_frames=0)
t("fix anatomy", "fix_clip", clip="c3", checks=[{"type": "anatomy"}])
t("fix anatomy one-frame clip", "fix_clip", clip="c2", checks=[{"type": "anatomy", "side": "r", "fingers": False}])
t("fix clearance spread", "fix_clip", clip="c3", checks=[{"type": "clearance", "max_cm": 0.0}], spread_frames=2)
t("scan one-frame clip", "scan_clip", clip="c2", checks=[{"type": "pop"}, {"type": "hold", "side": "l"}])
t("save missing", "save_clip", clip="nope")
t("save bad name", "save_clip", clip="../../evil")
t("save fbx", "save_clip", clip="c3", formats=["fbx"])
t("render bad view", "render", views=["x"])
t("render empty views", "render", views=[])
lab.close()
print("\nBUGS:", len(bad))
for b in bad: print(" -", b[0], "|", b[1])
sys.exit(1 if bad else 0)
